# Generated by Django 4.2.30 on 2026-08-01 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_animaux', models.CharField(help_text='ex: Poulets de chair, Porcs, Pondeuses, Bovins', max_length=100)),
                ('nombre_tetes', models.IntegerField(default=0)),
                ('date_acquisition', models.DateField()),
                ('batiment', models.CharField(blank=True, help_text='ex: Poulailler 1, Enclos B', max_length=100, null=True)),
                ('statut_sanitaire', models.CharField(default='Bon', help_text='Vaccinations à jour, Traitement en cours', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='ex: Parcelle Nord, Champ A', max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en Hectares', max_digits=8)),
                ('type_sol', models.CharField(blank=True, help_text='ex: Argileux, Ferralitique', max_length=100, null=True)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variete', models.CharField(help_text='ex: Maïs hybride, Cacao Trinitario, Bananier Plantain', max_length=100)),
                ('type_culture', models.CharField(choices=[('VIVRIERE', 'Culture Vivrière'), ('RENTE', 'Culture de Rente'), ('MARAICHERE', 'Culture Maraîchère')], default='VIVRIERE', max_length=30)),
                ('date_semis', models.DateField()),
                ('date_recolte_prevue', models.DateField(blank=True, null=True)),
                ('quantite_semee', models.DecimalField(decimal_places=2, default=0.0, help_text='en kg ou Plants', max_digits=10)),
                ('rendement_estime', models.DecimalField(decimal_places=2, default=0.0, help_text='en Tonnes ou kg', max_digits=10)),
                ('statut', models.CharField(choices=[('EN_CROISSANCE', 'En Croissance'), ('RECOLTE_EN_COURS', 'Récolte en Cours'), ('TERMINEE', 'Terminée'), ('PERDUE', 'Perdue')], default='EN_CROISSANCE', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='cultures.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(help_text='ex: Désherbage, Engrais, Vaccination, Alimentation', max_length=100)),
                ('date_activite', models.DateField()),
                ('description', models.TextField()),
                ('cout_associe', models.DecimalField(decimal_places=2, default=0.0, help_text='en FCFA', max_digits=10)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='cultures.culture')),
                ('elevage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='cultures.elevage')),
                ('employe_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employe')),
            ],
        ),
    ]
