# Generated by Django 4.2.30 on 2026-09-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteagricole',
            name='preuve_video',
            field=models.FileField(blank=True, help_text="Vidéo de preuve de l'activité", null=True, upload_to='activites/videos/'),
        ),
    ]
