# Generated by Django 4.2.30 on 2026-09-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0002_activiteagricole_preuve_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteagricole',
            name='preuve_video_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
    ]
