# Generated by Django 4.2.30 on 2026-08-01 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_categorie', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], default='DEPENSE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('VENTE', 'Vente'), ('ACHAT', 'Achat'), ('DEPENSE', 'Dépense'), ('REVENU', 'Revenu')], default='VENTE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=14)),
                ('description', models.CharField(help_text='ex: Vente de 50 sacs de maïs à Grossiste Yaoundé', max_length=255)),
                ('date_transaction', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money (MTN/Orange)'), ('VIREMENT', 'Virement Bancaire'), ('CHEQUE', 'Chèque')], default='CASH', max_length=50)),
                ('reference_recu', models.CharField(blank=True, help_text='N° de recu ou référence Mobile Money', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.categorietransaction')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
