# Generated by Django 4.2.30 on 2026-08-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='justificatif_photo',
            field=models.ImageField(blank=True, help_text='Photo du reçu ou de la facture', null=True, upload_to='justificatifs/'),
        ),
    ]
