import os
import django
from django.db import connection, transaction

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'agrisuivi_backend.settings')
django.setup()

sql = '''
CREATE TABLE IF NOT EXISTS authentication_customuser (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    password varchar(128) NOT NULL,
    last_login timestamp with time zone NULL,
    is_superuser boolean NOT NULL,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL,
    last_name varchar(150) NOT NULL,
    email varchar(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role varchar(30) NOT NULL,
    phone varchar(30) NULL,
    avatar varchar(100) NULL,
    is_active_employee boolean NOT NULL
);
CREATE TABLE IF NOT EXISTS authentication_customuser_groups (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);
CREATE TABLE IF NOT EXISTS authentication_customuser_user_permissions (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);
CREATE INDEX IF NOT EXISTS authentication_customuser_username_3dffdf84_like ON authentication_customuser (username varchar_pattern_ops);
CREATE UNIQUE INDEX IF NOT EXISTS authentication_customuse_customuser_id_group_id_8a637646_uniq ON authentication_customuser_groups (customuser_id, group_id);
ALTER TABLE authentication_customuser_groups ADD CONSTRAINT authentication_custo_customuser_id_a7d1343c_fk_authentic FOREIGN KEY (customuser_id) REFERENCES authentication_customuser (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE authentication_customuser_groups ADD CONSTRAINT authentication_custo_group_id_c5ef1d10_fk_auth_grou FOREIGN KEY (group_id) REFERENCES auth_group (id) DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS authentication_customuser_groups_customuser_id_a7d1343c ON authentication_customuser_groups (customuser_id);
CREATE INDEX IF NOT EXISTS authentication_customuser_groups_group_id_c5ef1d10 ON authentication_customuser_groups (group_id);
CREATE UNIQUE INDEX IF NOT EXISTS authentication_customuse_customuser_id_permission_923704b1_uniq ON authentication_customuser_user_permissions (customuser_id, permission_id);
ALTER TABLE authentication_customuser_user_permissions ADD CONSTRAINT authentication_custo_customuser_id_33d2a5f7_fk_authentic FOREIGN KEY (customuser_id) REFERENCES authentication_customuser (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE authentication_customuser_user_permissions ADD CONSTRAINT authentication_custo_permission_id_e47332af_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES auth_permission (id) DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS authentication_customuser__customuser_id_33d2a5f7 ON authentication_customuser_user_permissions (customuser_id);
CREATE INDEX IF NOT EXISTS authentication_customuser__permission_id_e47332af ON authentication_customuser_user_permissions (permission_id);
'''

with transaction.atomic():
    with connection.cursor() as cursor:
        cursor.execute(sql)
        cursor.execute(
            "SELECT 1 FROM django_migrations WHERE app=%s AND name=%s",
            ['authentication', '0001_initial'],
        )
        exists = cursor.fetchone() is not None
        if not exists:
            cursor.execute(
                "INSERT INTO django_migrations (app, name, applied) VALUES (%s, %s, NOW())",
                ['authentication', '0001_initial'],
            )
            print('Migration authentication.0001_initial enregistrée.')
        else:
            print('Migration authentication.0001_initial déjà présente.')

        cursor.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name LIKE 'authentication_customuser%';")
        rows = cursor.fetchall()
        print('Tables auth existantes:', rows)

print('Correction exécutée.')
