import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "agrisuivi_backend.settings")
django.setup()

from django.db import connection

sql_create_auditlog = """
CREATE TABLE IF NOT EXISTS "tracabilite_auditlog" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "nom_utilisateur" varchar(150) NULL,
    "role_utilisateur" varchar(50) NULL,
    "type_action" varchar(20) NOT NULL,
    "module" varchar(100) NOT NULL,
    "description" text NOT NULL,
    "ip_address" inet NULL,
    "created_at" timestamp with time zone NOT NULL,
    "utilisateur_id" bigint NULL
);
"""

sql_fk = """
ALTER TABLE "tracabilite_auditlog" ADD CONSTRAINT "tracabilite_auditlog_utilisateur_id_fk" FOREIGN KEY ("utilisateur_id") REFERENCES "authentication_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
"""

with connection.cursor() as cursor:
    cursor.execute("SELECT schema_name FROM tenants_client")
    schemas = [r[0] for r in cursor.fetchall()]

for schema in schemas:
    if schema == 'public': continue
    print(f"Creating AuditLog table in {schema}...")
    with connection.cursor() as cursor:
        cursor.execute(f'SET search_path TO {schema}')
        cursor.execute(sql_create_auditlog)
        try:
            cursor.execute(sql_fk)
        except Exception as e:
            pass # FK might already exist or something
        
        # We also need to fix the django_migrations if needed, but creating the table is enough for the login to work.
        cursor.execute("SELECT * FROM django_migrations WHERE app='tracabilite'")
        if not cursor.fetchall():
            cursor.execute("INSERT INTO django_migrations (app, name, applied) VALUES ('tracabilite', '0001_initial', NOW())")
            
print("Fix completed.")
