# Generated by Django 4.2.30 on 2026-08-01 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(blank=True, max_length=150, null=True)),
                ('role_utilisateur', models.CharField(blank=True, max_length=50, null=True)),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('EXPORT', 'Exportation / Rapport')], default='CREATION', max_length=20)),
                ('module', models.CharField(help_text='ex: Stocks, Cultures, Employés, Finances', max_length=100)),
                ('description', models.TextField(help_text="Détail lisible de l'opération effectuée")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
