# Generated by Django 4.2.30 on 2026-09-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracabilite', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='video_url',
            field=models.URLField(blank=True, help_text="URL de la vidéo associée à l'activité", max_length=500, null=True),
        ),
    ]
