# Generated by Django 4.2.30 on 2026-09-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tenant_schema',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Schéma du tenant (exploitation)'),
        ),
    ]
