# Generated by Django 4.2.30 on 2026-08-01 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_article', models.CharField(choices=[('INTRANT', 'Intrant (Engrais/Semences/Pesticides)'), ('RECOLTE', 'Produit Récolté'), ('EQUIPEMENT', 'Outillage / Équipement'), ('ALIMENTATION', 'Aliment pour Bétail'), ('AUTRE', 'Autre')], default='INTRANT', max_length=30)),
                ('quantite_en_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=10.0, help_text="Seuil minimum déclenchant l'alerte réapprovisionnement", max_digits=12)),
                ('unite_mesure', models.CharField(default='kg', help_text='ex: kg, Litres, Sacs, Unités, Tonnes', max_length=30)),
                ('prix_unitaire_moyen', models.DecimalField(decimal_places=2, default=0.0, help_text='en FCFA', max_digits=12)),
                ('emplacement', models.CharField(blank=True, help_text='ex: Magasin principal, Hangar B', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie / Utilisation'), ('PERTE', 'Perte / Avarie')], default='ENTREE', max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0.0, help_text='en FCFA', max_digits=12)),
                ('motif', models.CharField(blank=True, help_text="ex: Achats d'engrais NPK, Semis du Champ Nord", max_length=255, null=True)),
                ('date_mouvement', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stocks.articlestock')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articlestock',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='stocks.categoriestock'),
        ),
    ]
