# Generated by Django 4.2.30 on 2026-07-30 14:21

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'exploitation")),
                ('owner_name', models.CharField(max_length=150, verbose_name='Nom du propriétaire')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Email du propriétaire')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone')),
                ('region', models.CharField(default='Centre', max_length=100, verbose_name='Région (Cameroun)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Statut Actif')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
