# Generated by Django 4.2.30 on 2026-08-16 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('CONGE', 'Congé')], default='PRESENT', max_length=20)),
                ('heures_travaillees', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='employes.employe')),
            ],
            options={
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
